---
jupyter:
  jupytext:
    formats: Rmd,ipynb
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.9.1
  kernelspec:
    display_name: R
    language: R
    name: ir
---

# Set up

```{r}
if (!require("xfun")) install.packages("xfun")

pkgs <- c(
  'urca', 'uroot', 'vars', 'forecast', 'dynlm', 'tsDyn',
  'lubridate', 'tsbox', 'timetk', 'xts', 'tsibble',
  'tidyverse', 'readr', 'vroom', 'readxl', 'writexl', 
  'rlist', 'here', 'forcats', "janitor",
  'extrafont', 'patchwork', 'hrbrthemes', 'ggthemes', 'ggsci', 'scales',
  'kableExtra', 'gt', 'reshape2'
)
xfun::pkg_attach2(pkgs, message = TRUE)

loadfonts(device = "win", quiet = TRUE)
setwd(here())
```

```{r}
# source("R/oaeTS.R", encoding = "UTF-8")
# year_now <- 2563
```

# Read data and Convert to long format

```{r}
months_th <- c(
  'ม.ค.' = 1, 
  'ก.พ.' = 2, 
  'มี.ค.' = 3, 
  'เม.ย.'= 4, 
  'พ.ค.' = 5, 
  'มิ.ย.' = 6,
  'ก.ค.' = 7, 
  'ส.ค.' = 8, 
  'ก.ย.' = 9, 
  'ต.ค.' = 10, 
  'พ.ย.' = 11, 
  'ธ.ค.' = 12
)
```

## Farmgate price
รวมไฟล์ราคา แล้ว save เป็น RDS

```{r}
read_price_rice_fg <- function(root, filename) {
  
  path = paste0(root, filename)
  sheets = excel_sheets(path)
  data = data.frame()

  for (i in sheets){
    dt =
      read_excel(path, skip=3, sheet=paste(i), na = c("-","",0)) %>%
      pivot_longer(-1, names_to='month_th', values_to='value') %>%
      filter(month_th %in% names(months_th)) %>%
      mutate(year = as.numeric(i) - 543) %>%
      mutate(month = months_th[month_th]) %>%
      mutate(date = as.Date(paste("1", 
                                  as.character(month), 
                                  as.character(year), 
                                  sep="/"),
                            format='%d/%m/%Y')
            )
      data = rbind(data, dt)
  }
  
  names(data)[1] = 'place'
  
  return(data)
}
```

```{r}
root <- "data/rice/farmgate/"

rhfg <- read_price_rice_fg(root, "rhfg.xlsx") %>% mutate(price_id = 'RHFG')
rwfg <- read_price_rice_fg(root, "rwfg.xlsx") %>% mutate(price_id = 'RWFG')
rgfg <- read_price_rice_fg(root, "rgfg.xlsx") %>% mutate(price_id = 'RGFG')

rice_fg <- rbind(rhfg, rwfg, rgfg) %>%
  select(date, price_id, place, value) %>%
  filter(date < '2020-01-01')

# saveRDS(rice_fg, 'data/rice/rice_fg.rds')
rice_fg
```

## Wholesale price
รวมไฟล์ราคา แล้ว save เป็น RDS

```{r}
# define function
read_price_ws <- function(year, month) {

  path <- glue::glue("data/rice/wholesale/ws{year}.xls")
  read_excel(
    path, skip = 1, 
    sheet = month.abb[month] %>% tolower(), 
    na = c("-", "", 0)
  ) %>%
    suppressMessages() %>%
    rename_at(1:2, ~c("price_id", "price_name")) %>%
    pivot_longer(
      -(1:2), 
      names_to = 'day', 
      values_to = 'value'
    ) %>%
    filter(day %in% as.character(1:31)) %>%
    mutate(
      date = as.Date(glue::glue("{year-543}-{month}-{day}")),
      place = 'bangkok'
    ) %>%
    drop_na(value, date) %>%
    select(date, price_id, place, value)
}

# test
# year <- 2555
# month <- 1
# read_price_ws(year, month)
```

```{r}
rice_ws <- expand_grid(
  year = 2547:2562, 
  month = 1:12
) %>% 
  pmap(read_price_ws) %>%
  reduce(bind_rows)

# saveRDS(rice_ws, 'data/rice/rice_ws.rds')
```

```{r}
rice_ws
```

## Export price
รวมไฟล์ราคา แล้ว save เป็น RDS

```{r}
read_price_ex_th <- function(year, month) {
  
  first_day_of_month <- ymd(glue::glue("{year-543}-{month}-1"))
  last_day_of_month  <- first_day_of_month %>% ceiling_date(unit = "month") - 1
  d <- seq(first_day_of_month, by = 1, length.out = 7)
  d <- seq(d[wday(d)==6], by = 7, length.out = 5)
  d <- d[lubridate::month(d) == month]
  if(length(d) == 4) {
    d[5] <- last_day_of_month
  }
  
  path <- glue::glue("data/rice/export_th/ex{year}.xlsx")
  read_excel(
    path, skip = 2,
    sheet = month.abb[month] %>% tolower(), 
    na = c("-", "", 0)
  ) %>%
    suppressMessages() %>%
    rename_at(1:2, ~c("price_id", "price_name")) %>%
    select(1:7) %>%
    drop_na(price_id) %>%
    pivot_longer(
      -(1:2), 
      names_to = 'week', 
      values_to = 'value'
    ) %>%
    drop_na(value) %>%
    mutate(
      date = d[week %>% as.numeric],
      place = 'bangkok'
    ) %>%
    select(date, price_id, place, value)
}

# test
# year <- 2555
# month <- 1
# read_price_ex(year, month)
```

```{r}
rice_ex_th <- expand_grid(
  year = 2547:2562, 
  month = 1:12
) %>% 
  pmap(read_price_ex_th) %>%
  reduce(bind_rows)

# saveRDS(rice_ex_th, 'data/rice/rice_ex_th.rds')
```

```{r}
rice_ex_th
```

## Combine prices from 3 markets

```{r}
rice_price <- bind_rows(rice_fg, rice_ws, rice_ex_th)
# saveRDS(rice_price, 'data/rice/rice_price.rds')
```

```{r}
rice_price
```

```{r}
rice_price <- readRDS('data/rice/rice_price.rds')
rice_price
```

# Convert to wide format

```{r}
prices_selected <- c(
  "RHFG",                 # hommali rice farmgate
  "RHWS00BO", "RHWS00BN", # hommali rice wholesale
  "RHXB00BO", "RHXB00BN", # hommali rice export in baht
  "RWFG",                 # white rice farmgate
  "RWWS05GN",             # white rice wholesale 
  "RWXB05GU"              # white rice export in baht
)
```

```{r}
rice_price_wide <- rice_price %>%
  arrange(price_id) %>%
  filter(
    place %in% c("bangkok", "เฉลี่ยทั้งประเทศ"),
    price_id %in% prices_selected
  ) %>%
  pivot_wider(
    id = date,
    names_from = price_id,
    values_from = value
  ) %>% 
  arrange(date) #%>% write_xlsx("data/rice/rice_price_wide.xlsx")
```

```{r}
rice_price_wide
```

# Convert to monthly

```{r}
rice_price_wide_m <- rice_price_wide %>%
  mutate(
    date_floor = floor_date(date, unit = "month")
  ) %>%
  group_by(date_floor) %>%
  summarize(across(starts_with("R"), ~ mean(.x, na.rm = TRUE)))

rice_price_wide_m
# rice_price_wide_m %>% write_xlsx("data/rice/rice_price_wide_m.xlsx")
```

# Clean

```{r}
rice_price_wide_m_clean <- rice_price_wide_m %>%
  mutate(
    phf = RHFG,
    phw = ifelse(is.na(RHWS00BN), RHWS00BO, RHWS00BN),
    phx = ifelse(is.na(RHXB00BN), RHXB00BO, RHXB00BN),
    pwf = RWFG,
    pww = RWWS05GN,
    pwx = RWXB05GU
  ) %>%
  select(c("date" = date_floor), starts_with("p"))
```

```{r}
rice_price_wide_m_clean
```

# Add dummy variables

```{r}
# dummy years ช่วงวิกฤตอาหารครั้งที่ 1
start_foodcrisis <- ymd('2007-11-01')
end_foodcrisis   <- ymd('2008-06-01')

# dummy years ช่วงนโยบายจำนำข้าวทุกเมล็ดของ นายก ยิ่งลักษณ์
start_pledge <- ymd('2011-09-01')
end_pledge   <- ymd('2014-01-01')
```

```{r}
rice_price_wide_m_clean <- rice_price_wide_m_clean %>%
  mutate(
    d_foodcrisis = ifelse(
      date >= start_foodcrisis & date <= end_foodcrisis, 1, 0),
    d_pledge = ifelse(
      date >= start_pledge & date <= end_pledge, 1, 0)
  )

rice_price_wide_m_clean
# rice_price_wide
```

```{r}
saveRDS(rice_price_wide_m_clean, 'data/rice/clean/rice_price.rds')
write_xlsx(rice_price_wide_m_clean, 'data/rice/clean/rice_price.xlsx')
```

```{r}
options(repr.plot.bg = "grey80")
```

# กราฟ

```{r}
rice_price_wide_m_clean %>% filter(date >= '2004-01-01') %>%
  ggplot(aes(x=date)) +
    geom_line( aes(y=phf, color = 'เกษตรกรขายได้')) +
    geom_line( aes(y=phw, color = 'ขายส่ง')) +
    geom_line( aes(y=phx, color = 'ส่งออก')) +
    scale_color_d3() +
    expand_limits(y = 0) +
    scale_y_continuous(label = comma) +
    labs(title = 'ราคาข้าวหอมมะลิ 3 ตลาด',
         x =  "ปี",
         y = 'บาท/ตัน'
        ) +
    theme_ipsum(
      base_size = 16,
      base_family = "Athiti Light",
      axis_title_size = 16
    ) + 
    theme(
      legend.position = c(1, 1),
      legend.direction = 'horizontal',
      legend.justification = 'right',
      legend.title = element_blank(),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      panel.background = element_rect(fill = "transparent",colour = NA),
      plot.background = element_rect(fill = "transparent",colour = NA)
    ) +
    scale_x_date(date_breaks = '2 years',
                 labels = function(x) year(x)+543
                 )
```

```{r}
rice_price_wide_m_clean %>% filter(date >= '2004-01-01') %>%
  ggplot(aes(x=date)) +
    geom_line( aes(y=pwf, color = 'เกษตรกรขายได้')) +
    geom_line( aes(y=pww, color = 'ขายส่ง')) +
    geom_line( aes(y=pwx, color = 'ส่งออก')) +
    scale_color_d3() +
    expand_limits(y = 0) +
    scale_y_continuous(label = comma) +
    labs(title = 'ราคาข้าวเจ้าขาว 3 ตลาด',
         x =  "ปี",
         y = 'บาท/ตัน'
        ) +
    theme_ipsum(
      base_size = 16,
      base_family = "Athiti Light",
      axis_title_size = 16
    ) +
    theme(
      legend.position = c(1, 1),
      legend.direction = 'horizontal',
      legend.justification = 'right',
      legend.title = element_blank()
    ) +
    scale_x_date(date_breaks = '2 years',
                 labels = function(x) year(x)+543
                 )
```

# Backup

```{r}
# rice_fg_wide = rice_price %>%
#   filter(grepl('FG', price_id)) %>%
#   filter(!is.na(amount)) %>%
#   filter(!is.na(date)) %>%
#   left_join(tbl_admin_tha1, by=c("place" = "name_oae1")) %>%
#   mutate(place_id = str_replace_all(HASC_1, "TH.", "")) %>%
#   mutate(new_price_id=paste(price_id, place_id, sep="_")) %>%
#   mutate(month = floor_date(date, "month")) %>%
#   filter(new_price_id %in% prices) %>%
#   select(month, place, new_price_id, amount) %>%
#   group_by(month, new_price_id) %>%
#   summarise(amount = mean(amount)) %>%
#   spread(new_price_id, amount)

# write.xlsx(rice_price_wide, '../data/rice/rice_price_wide.xlsx')
```

```{r}
# prices = c("RHWS00BO", "RHWS00BN", # hommali rice wholesale
#            "RHXB00BO", "RHXB00BN", # hommali rice export
#            "RWWS05GO", "RWWS05GN", # white rice wholesale 
#            "RWXB05GU", # white rice export 
#            "RGWS10LO", "RGWS10LN", # glutinous wholesale
#            "RGXB10GF", "RGXB10GS", "RGXB10GU", "RGXB10LU" # glutinous export
#           )

# rice_price_wide = rice_price %>%
#     select(-place) %>%
#     filter(price_id %in% prices) %>%
#     filter(!is.na(date)) %>%
#     mutate(month = floor_date(date, "month")) %>%
#     mutate(new_price_id = substr(price_id,start = 1, stop = 4)) %>%
#     group_by(month, new_price_id) %>%
#     summarise(amount = mean(amount)) %>%
#     spread(new_price_id, amount) %>%
#     right_join(rice_fg_wide, by="month")
```

```{r}
# check <- rice_price %>%
#     filter(grepl('FG', price_id)) %>%
#     mutate(count = !is.na(amount)) %>%
#     group_by(place, price_id) %>%
#     summarise(sum = sum(count)) %>%
#     spread(price_id, sum)

# write.xlsx(check, '../data/rice/check.xlsx')
```

```{r}
# library(rio)
# data_list <- import_list("../data/data_dict.xlsx")

# A <- data_list$aa['aa']
# B <- data_list$bb['bb']
# C <- data_list$cc['cc']
# D <- data_list$d['d']
# E <- data_list$e['e']

# price_id_names <- unique(rice_price$price_id)

# tbl_rice_price <- crossing(A,B,C,D,E) %>% 
#     mutate(price_id = pmap_chr(., paste, sep="")) %>%
#     mutate(price_id = str_replace_all(price_id, "Z", "")) %>%
#     filter(price_id %in% price_id_names)

# tbl_rice_price <- tbl_price_rice %>%
#     left_join(data_list$aa) %>%
#     left_join(data_list$bb) %>%
#     left_join(data_list$cc) %>%
#     left_join(data_list$d) %>%
#     left_join(data_list$e) %>%
#     unite(price_name, c(aa_name, bb_name, cc_name, d_name, e_name), sep = " ", remove = FALSE) %>%
#     unite(price_name_th, c(aa_name_th, bb_name_th, cc_name_th, d_name_th, e_name_th), sep = " ", remove = FALSE) %>%
#     mutate(price_name = str_replace_all(price_name, "NA", "")) %>% 
#     mutate(price_name_th = str_replace_all(price_name_th, "NA", ""))

# write.xlsx(tbl_rice_price, '../data/rice/tbl_rice_price.xlsx')
```

```{r}
# count_by_price_id <- rice_price %>%
#     group_by(price_id) %>%
#     summarize(sum(!is.na(amount))) %>%
#     left_join(tbl_rice_price)
# write.xlsx(count_by_price_id, '../data/rice/count_by_price_id.xlsx')
```

```{r}
# write.xlsx(unique(rice_fg$place), 'changwat.xlsx')
```

```{r}
# tbl_admin_tha1 <- read_excel("data/tbl_admin_tha1.xlsx")
# tbl_admin_tha1

# prices = c("RGFG_0", #"RGFG_1", "RGFG_2", "RGFG_3",
#            "RGFG_KK", "RGFG_SN", "RGFG_UN", "RGFG_KL", "RGFG_MS",
#            "RHFG_0", #"RHFG_1", "RHFG_2", "RHFG_3", 
#            "RHFG_SU", "RHFG_NR", "RHFG_UR", "RHFG_SI", "RHFG_BR",
#            "RWFG_0", #"RWFG_1", "RWFG_2", "RWFG_3", 
#            "RWFG_NS", "RWFG_PC", "RWFG_KP", "RWFG_SH", "RWFG_PS"
#           )

# rice_fg_wide = rice_price %>%
#   filter(endsWith(price_id, "FG")) %>%
#   mutate(HASC_1 = sapply(place,
#                          lookup,
#                          tbl_admin_tha1, 
#                          key = 'name_th1', 
#                          alt = 'name_alt',
#                          val = 'HASC_1',
#                          simplify = TRUE)
#         ) %>%
#   left_join(tbl_admin_tha1, by=c('HASC_1')) %>%
#   mutate(place_id = str_replace_all(HASC_1, "TH.", "")) %>%
#   mutate(price_id = paste(price_id, place_id, sep="_")) %>%
#   mutate(date = floor_date(date, "month")) %>%
#   filter(price_id %in% prices) %>%
#   pivot_wider(id_cols = date,
#               names_from = price_id,
#               values_from = amount,
#               values_fn = list(amount = mean)
#              )

# rice_fg_wide
```

```{r}
# prices = c("RHWS00BO", "RHWS00BN", # hommali rice wholesale
#            "RHXB00BO", "RHXB00BN", # hommali rice export
#            "RWWS05GO", "RWWS05GN", # white rice wholesale 
#            "RWXB05GU", # white rice export 
#            "RGWS10LO", "RGWS10LN", # glutinous wholesale
#            "RGXB10GF", "RGXB10GS", "RGXB10GU", "RGXB10LU" # glutinous export
#           )

# rice_price_wide = rice_price %>%
#   select(-place) %>%
#   filter(price_id %in% prices) %>%
#   filter(!is.na(date)) %>% # there are some missing date due to week
#   mutate(date = floor_date(date, "month")) %>%
#   mutate(price_id = substr(price_id, start = 1, stop = 4)) %>%
#   pivot_wider(id_cols = date,
#               names_from = price_id,
#               values_from = amount,
#               values_fn = list(amount = mean)
#              )

# rice_price_wide = rice_fg_wide %>% left_join(rice_price_wide, by="date")
# rice_price_wide
```
