```{r}
# library(urca)
# library(aod)
# library(vars)
# library(tidyverse)
```

```{r}
source("../R/granger_ty.R")
```

```{r}
data(Canada)
```

```{r}
granger_ty(Canada) %>% select(-wald) %>% filter(chi2_pval < 0.1)
```

```{r}
data <- Canada
p <- 2
m <- 0

k <- ncol(data)
y_names <- colnames(data)

res <- expand.grid(x = y_names, y = y_names, stringsAsFactors = FALSE) %>%
  dplyr::filter(x != y)

fitted <- VAR(data, p = p + m)
coef_loc <- set_names(1:k, y_names) %>% imap( ~ k*(1:p)-(k-.x) )

res <- res %>% mutate(
  b = map(y, ~ fitted$varresult[[.]] %>% coef),
  Sigma = map(y, ~ fitted$varresult[[.]] %>% vcov),
  Terms = coef_loc[x] %>% unname,
  wald = pmap(list(b, Sigma, Terms), ~ wald.test(b = ..1, Sigma = ..2, Terms = ..3)),
  chi2_stat = map(wald, ~ .$result[['chi2']][['chi2']]),
  chi2_df = map(wald, ~ .$result[['chi2']][['df']]),
  chi2_pval =  map(wald, ~ .$result[['chi2']][['P']]),
) %>% select(-(b:Terms))
```

```{r}
res %>% select(-wald) %>%
  filter(chi2_pval < 0.1)
```

```{r}
granger_ty <- function(data, p = 1, m = 0, ...) {
  
  # get information from input
  k <- ncol(data) # number of endo variables
  endo_names <- colnames(data) # name of endo variables
  
  # initialize a tibble containing x = causing variable and y = effect variables
  res <- expand.grid(x = endo_names, y = endo_names, stringsAsFactors = FALSE) %>%
    dplyr::filter(x != y) %>% as_tibble()
  
  # fit VAR model with p+m lag
  fitted <- VAR(data, p = p + m)
  
  # compute index indicating position of coefficients associated with its own variable
  coef_idx <- set_names(1:k, endo_names) %>% imap( ~ k*(1:p)-(k-.x) )

  res %>% mutate(
    b     = map(y, ~ fitted$varresult[[.]] %>% coef), # coefficient
    Sigma = map(y, ~ fitted$varresult[[.]] %>% vcov), # covariance
    Terms = coef_idx[x] %>% unname, # position for restricting values to 0
    wald  = pmap(list(b, Sigma, Terms), 
                 ~ wald.test(b = ..1, Sigma = ..2, Terms = ..3)
                ),
    chi2_stat = map(wald, ~ .$result[['chi2']][['chi2']]),
    chi2_df   = map(wald, ~ .$result[['chi2']][['df']]),
    chi2_pval =  map(wald, ~ .$result[['chi2']][['P']]),
  ) %>% select(-(b:Terms))
}

granger_ty(Canada, p = 2, m = 1) %>% select(-wald)
```

```{r}
cof <- read.csv("http://christophpfeiffer.org/wp-content/uploads/2012/11/coffee_data.csv", 
                header=T, sep=";")
cof <- cof[complete.cases(cof),]
```

```{r}
cof1 <- cof[193:615,]

VARselect(cof[,2:3],lag=20,type="both")
```

```{r}
V.6 <- VAR(cof1[,2:3],p=6,type="both")
serial.test(V.6)
```

```{r}
V.6 %>% summary()
```

```{r}
wald.test
```

```{r}
V.7$varresult[[1]] %>% coef
```

```{r}
n_vars <- 2
n_lags <- 6

1:n_vars %>% map(
  ~ n_vars*(1:n_lags) - (n_vars-.x)
)
```

```{r}
x <- V.7$varresult[[1]] %>% coef
```

# cof1

```{r}
V.7<-VAR(cof1[,2:3],p=7,type="const", season = 12)
V.7$varresult
summary(V.7)
```

```{r}
wald.test(b=coef(V.7$varresult[[1]]), Sigma=vcov(V.7$varresult[[1]]), Terms=c(2,4,6,8,10,12))
```

```{r}
test1 <- wald.test(b=coef(V.7$varresult[[1]]), Sigma=vcov(V.7$varresult[[1]]), Terms=c(2,4,6,8,10,12))
```

```{r}
str(test1)
```

```{r}
a <- letters[1:5]
df <- expand.grid(x = a, y = a, stringsAsFactors = FALSE)
df
```

```{r}
df %>%
  filter(x != y)
```

```{r}
wald.test()
```

```{r}
data("Mandible", package = "lmtest")
fm <- lm(length ~ age, data = Mandible, subset=(age <= 28))
```

```{r}
fm %>% summary
```

```{r}
coeftest(fm)
```

```{r}
eq_e_r <- dynlm(e ~ L(e, 1:4) + , data = Canada)
eq_e_ur  <- update(eq_e_ur, . ~ . + L(prod, 1:4))
# eq_e_r  <- dynlm(e ~ L(e, 1:2) + L(prod, 1), data = Canada)
# eq_prod <- dynlm(prod ~ L(e, 1:3) + L(prod, 1:3), data = Canada)
```

```{r}
eq_e_ur %>% summary
```

```{r}
waldtest(eq_e_ur, eq_e_r)
```

```{r}
eq_e_r <- update(eq_e, . ~ ., - L(prod, 1:3))
```

```{r}
eq_e_r %>% summary()
```

```{r}
waldtest(eq_e, eq_e_r)
```

```{r}
library(lmtest)
library(dynlm)
library(tidyverse)
```

```{r}
data("UKDriverDeaths", package = "datasets")
uk <- log10(UKDriverDeaths)
dfm1 <- dynlm(uk ~ L(uk, 1) + L(uk, 12))
dfm1 %>% summary()
```

```{r}
dfm2 <- update(dfm1, . ~ . -L(uk, 12))
dfm2 %>% summary()
```

```{r}
dfm2 <- dynlm(uk ~ L(uk, 1))
dfm2 %>% summary()
```

```{r}

```

```{r}
Vcov <- vcov(dfm1, dfm2)
```

```{r}
waldtest(dfm1, dfm2)
```

```{r}
data("M1Germany")
```

```{r}
histfm1 <- dynlm(
  d(logm1) ~ d(L(loggnp, 2)) + d(interest) + d(L(interest)) + d(logprice) + L(logm1) + L(loggnp) + L(interest) + season(logm1, ref = 4),
  data = M1Germany, 
  start = c(1961, 1), end = c(1990, 2)
)
```

```{r}
histfm2 <- dynlm(
  d(logm1) ~ d(interest) + d(L(interest)) + d(logprice) + L(logm1) + L(loggnp) + L(interest) + season(logm1, ref = 4),
  data = M1Germany, 
  start = c(1961, 1), end = c(1990, 2)
)
```

```{r}
waldtest(histfm1, histfm2)
```

```{r}

```
